Finanstilsynet/Models/Laptop.cs
namespace Models;

public partial class Laptop
{
    public int ModelId { get; set; }

    public int? Speed { get; set; }

    public int? Ram { get; set; }

    public int? HardDisk { get; set; }

    public decimal? Screen { get; set; }

    public int? Price { get; set; }

    public virtual Product Model { get; set; } = null!;
}

Finanstilsynet/Models/Printer.cs
namespace Models;

public partial class Printer
{
    public int ModelId { get; set; }

    public string? Color { get; set; }

    public string? PrinterType { get; set; }

    public int? Price { get; set; }

    public virtual Product Model { get; set; } = null!;
}

Finanstilsynet/Models/Product.cs
using Finanstilsynet.Models;

namespace Models;

public partial class Product
{
    public int ModelId { get; set; }

    public string MakerId { get; set; } = null!;

    public string? ProductType { get; set; }

    public virtual Laptop? Laptop { get; set; }

    public virtual Maker Maker { get; set; } = null!;

    public virtual Pc? Pc { get; set; }

    public virtual Printer? Printer { get; set; }
}

Finanstilsynet/ViewModels/DashboardViewModel.cs
namespace ViewModels
{
    public class DashboardViewModel
    {
        public string ProductType { get; set; }
        public string MakerID { get; set; }
        public string MakerColor { get; set; }
        public int ProductCount { get; set; }
    }
}

Finanstilsynet/ViewModels/ProductViewModel.cs
namespace ViewModels
{
    public class ProductViewModel
    {
        public int ModelID { get; set; }
        public string MakerID { get; set; }
        public string Product_Type { get; set; }
        public int? Laptop_Speed { get; set; }
        public int? Laptop_RAM { get; set; }
        public int? Laptop_HardDisk { get; set; }
        public decimal? Laptop_Screen { get; set; }
        public int? PC_Speed { get; set; }
        public int? PC_RAM { get; set; }
        public int? PC_HardDisk { get; set; }
        public string PC_ReadDrive { get; set; }
        public string Printer_Color { get; set; }
        public string Printer_Type { get; set; }
        public int? Product_Price { get; set; }
        public string Maker_Color { get; set; }
    }
}

Finanstilsynet/Controllers/ProductCatalogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models;
using Repository;
using Repository.Interfaces;
using System.Diagnostics;
using System.Reflection;
using ViewModels;
using static System.Formats.Asn1.AsnWriter;

namespace Controllers
{
    public class ProductCatalogController : Controller
    {
        private readonly ILogger<ProductCatalogController> _logger;

        private readonly IGetData _getData;
        private readonly IAddData _addData;
        private readonly IDeleteData _deleteData;
        private readonly IUpdateData _updateData;

        public IActionResult Info()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        public ProductCatalogController(ILogger<ProductCatalogController> logger, IAddData addData, IDeleteData deleteData, IUpdateData updateData, IGetData getData)
        {
            _addData = addData;
            _deleteData = deleteData;
            _updateData = updateData;
            _getData = getData;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var productCatalog = await _getData.GetProductCatalogAsync();
            return View(productCatalog);
        }

        [Authorize]
        public async Task<IActionResult> Dashboard()
        {
            var productCatalogByMaker = await _getData.GetProductCatalogByMakerAsync();
            return View(productCatalogByMaker);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize]
        public async Task<IActionResult> PersonalComputers()
        {
            var productCatalog = await _getData.GetProductCatalogAsync();
            return View(productCatalog);
        }

        public async Task<IActionResult> EditPersonalComputer(int? modelID)
        {
            if (modelID == null)
            {
                return NotFound();
            }

            var product = await _getData.GetProductByModelIDAsync(modelID.Value);
            if (product == null)
            {
                return NotFound();
            }
            return View("PersonalComputer", product);
        }

        public async Task<IActionResult> DeletePersonalComputer(int? modelID)
        {
            if (modelID == null)
            {
                return NotFound();
            }

            await _deleteData.ProductAsync(modelID.Value);
            return RedirectToAction(nameof(PersonalComputers));
        }

        [HttpPost]
        public async Task<IActionResult> SaveNewPersonalComputer([FromForm] Pc pc)
        {
            if (pc == null)
            {
                return NotFound();
            }

            await _addData.AddPcAsync(pc);
            return RedirectToAction(nameof(PersonalComputers));
        }

        public async Task<IActionResult> NewPersonalComputer()
        {
            var model = new Pc { };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePc([FromForm] Pc pc)
        {
            if (pc == null)
            {
                return NotFound();
            }

            try
            {
                await _updateData.UpdatePcAsync(pc);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating the PC." + ex.Message);
                return View(pc);
            }

            return RedirectToAction(nameof(PersonalComputers));
        }

        [Authorize]
        public async Task<IActionResult> Printers()
        {
            var productCatalog = await _getData.GetProductCatalogAsync();
            return View(productCatalog);
        }

        public async Task<IActionResult> EditPrinter(int? modelID)
        {
            if (modelID == null)
            {
                return NotFound();
            }

            var product = await _getData.GetProductByModelIDAsync(modelID.Value);
            if (product == null)
            {
                return NotFound();
            }
            return View("Printer", product);
        }

        public async Task<IActionResult> DeletePrinter(int? modelID)
        {
            if (modelID == null)
            {
                return NotFound();
            }

            await _deleteData.ProductAsync(modelID.Value);
            return RedirectToAction(nameof(Printers));
        }

        [HttpPost]
        public async Task<IActionResult> SaveNewPrinter([FromForm] Printers printer)
        {
            if (printer == null)
            {
                return NotFound();
            }

            await _addData.AddPrinterAsync(printer);
            return RedirectToAction(nameof(Printers));
        }

        public async Task<IActionResult> NewPrinter()
        {
            var model = new Printer { };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePrinter([FromForm] Printer printer)
        {
            if (printer == null)
            {
                return NotFound();
            }

            try
            {
                await _updateData.UpdatePrinterAsync(printer);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating the Printer." + ex.Message);
                return View(printer);
            }

            return RedirectToAction(nameof(Printers));
        }
        [Authorize]
        public async Task<IActionResult> Laptops()
        {
            var productCatalog = await _getData.GetProductCatalogAsync();
            return View(productCatalog);
        }

        public async Task<IActionResult> EditLaptops(int? modelID)
        {
            if (modelID == null)
            {
                return NotFound();
            }

            var product = await _getData.GetProductByModelIDAsync(modelID.Value);
            if (product == null)
            {
                return NotFound();
            }
            return View("Laptop", product);
        }

        public async Task<IActionResult> DeleteLaptop(int? modelID)
        {
            if (modelID == null)
            {
                return NotFound();
            }

            await _deleteData.ProductAsync(modelID.Value);
            return RedirectToAction(nameof(Laptops));
        }

        [HttpPost]
        public async Task<IActionResult> SaveNewLaptop([FromForm] Laptop laptop)
        {
            if (laptop == null)
            {
                return NotFound();
            }

            await _addData.AddLaptopAsync(laptop);
            return RedirectToAction(nameof(Laptops));
        }

        public async Task<IActionResult> NewLaptop()
        {
            var model = new Laptop { };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateLaptop([FromForm] Laptop laptop)
        {
            if (laptop == null)
            {
                return NotFound();
            }

            try
            {
                await _updateData.UpdateLaptopAsync(laptop);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating the Laptop." + ex.Message);
                return View(laptop);
            }

            return RedirectToAction(nameof(Laptops));
        }
    }
}
public class Printers
    {
    }
public class Laptops
    {
    }

Finanstilsynet/Views/ProductCatalog/Dashboard.cshtml
@using ViewModels
@{
    ViewData["Title"] = "Products";
}

@model IEnumerable<DashboardViewModel>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script> 

<div class="content">
    <div class="content__header">
        <nav class="mt-1" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
            </ol>
        </nav>
        <hr class="mt-0">
    </div>
    <div class="content__body">
        <div class="col-12 col-md-12 pb-6">
            <div class="form-floating">
                <canvas id="myPieChart" style="max-width: 100%; height: 600px; max-height:600px;"></canvas>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var data = @Html.Raw(Json.Serialize(Model));

        const labels = data.map(item => item.makerID);
        const datasetData = data.map(item => item.productCount);
        const backgroundColors = data.map(item => item.makerColor); 

        var ctx = document.getElementById('myPieChart').getContext('2d');

        const datasets = data.reduce((acc, curr) => {
            const productTypeIndex = acc.findIndex(dataset => dataset.label === curr.productType);
            if (productTypeIndex === -1) {
                acc.push({
                    label: curr.productType,
                    data: [curr.productCount],
                    backgroundColor: [curr.makerColor],
                    hoverOffset: 4
                });
            } else {
                acc[productTypeIndex].data.push(curr.productCount);
                acc[productTypeIndex].backgroundColor.push(curr.makerColor);
            }
            return acc;
        }, []);

        const chart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: labels,
                datasets: datasets
            },
            options: {
                plugins: {
                    tooltip: {
                        callbacks: {
                            label: function (context) {
                                var label = context.dataset.label || '';
                                if (label) {
                                    label += ': ';
                                }
                                if (context.parsed.y !== null) {
                                    label += context.parsed.y;
                                }
                                return label;
                            }
                        }
                    }
                }
            }
        });
    </script>
}

@* @section Scripts {
    <script type="text/javascript"> 
        // var data = @Html.Raw(Json.Serialize(Model));

        // var processedData = data.reduce((acc, curr) => {
        //     const productTypeIndex = acc.findIndex(item => item.productType === curr.productType);
        //     if (productTypeIndex === -1) {
        //         acc.push({
        //             productType: curr.productType,
        //             productCount: curr.productCount,
        //             makerColor: curr.makerColor // Use the first encountered color
        //         });
        //     } else {
        //         // Aggregate productCounts, but do not alter the already chosen makerColor
        //         acc[productTypeIndex].productCount += curr.productCount;
        //     }
        //     return acc;
        // }, []);

        // // Now create your labels, datasetData, and backgroundColors arrays
        // const labels = processedData.map(item => item.productType);
        // const datasetData = processedData.map(item => item.productCount);
        // const backgroundColors = processedData.map(item => item.makerColor);

        // var ctx = document.getElementById('myPieChart').getContext('2d');

        // const chart = new Chart(ctx, {
        //     type: 'pie',
        //     data: {
        //         labels: labels, // Labels for each productType
        //         datasets: [{
        //             data: datasetData, // Aggregated productCounts
        //             backgroundColor: backgroundColors, // Representative backgroundColors
        //             hoverOffset: 4
        //         }]
        //     },
        //     options: {
        //         plugins: {
        //             tooltip: {
        //                 callbacks: {
        //                     label: function (context) {
        //                         var label = labels[context.dataIndex] || '';
        //                         if (label) {
        //                             label += ': ';
        //                         }
        //                         label += context.parsed;
        //                         return label;
        //                     }
        //                 }
        //             }
        //         }
        //     }
        // });

     </script>
}  *@

@* @section Scripts {
    <script type="text/javascript">
        var data = @Html.Raw(Json.Serialize(Model));

        const labels = data.map(item => item.productType);
        const backgroundColors = data.map(item => item.makerColor);

        const datasetData = data.map(item => item.productCount);

        var ctx = document.getElementById('myPieChart').getContext('2d');

        const chart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: labels, 
                datasets: [{
                    label: "Product Count",
                    data: datasetData,
                    backgroundColor: backgroundColors,
                    hoverOffset: 4
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top', 
                    },
                    tooltip: {
                        callbacks: {
                            label: function (context) {
                                var label = context.label || '';
                                if (label) {
                                    label += ': ';
                                }
                                label += context.parsed;
                                return label;
                            }
                        }
                    }
                }
            }
        });
    </script>
} *@

Finanstilsynet/Views/ProductCatalog/Laptop.cshtml
@using Models

@model Laptop

@{
    ViewData["Title"] = "Manage Laptop";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-3">
    <h2>@ViewData["Title"]</h2>

    <form id="personalComputerForm" asp-action="UpdateLaptop" asp-controller="ProductCatalog" method="post">
        <div class="form-group">
            <label asp-for="ModelId">Model ID</label>
            <input asp-for="ModelId" class="form-control" disabled />
            <input type="hidden" asp-for="ModelId" />
        </div>
        <div class="form-group">
            <label asp-for="Speed">PC speed</label>
            <input asp-for="Speed" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Ram">PC RAM</label>
            <input asp-for="Ram" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="HardDisk">Laptop hard disk</label>
            <input asp-for="HardDisk" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Screen">Laptop screen</label>
            <input asp-for="Screen" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" type="number" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <hr />
</div>

Finanstilsynet/Views/ProductCatalog/Laptops.cshtml
@using ViewModels

@model List<ProductViewModel>

@{
    ViewData["Title"] = "Manage Laptops";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mb-3">
    <h2>@ViewData["Title"]</h2>
    <hr />
    <table id="productTable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Model ID</th>
                <th>Laptop Speed</th>
                <th>Laptop RAM</th>
                <th>Laptop Hard Disk</th>
                <th>Screen</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                if (item.Product_Type.Trim().Equals("laptop", StringComparison.OrdinalIgnoreCase))
                {
                    <tr>
                        <td>@item.ModelID</td>
                        <td>@item.Laptop_Speed</td>
                        <td>@item.Laptop_RAM</td>
                        <td>@item.Laptop_HardDisk</td>
                        <td>@item.PC_HardDisk</td>
                        <td>@item.Laptop_Screen</td>
                        <td>@item.Product_Price</td>
                        <td>
                            <a asp-action="EditLaptop" asp-route-modelID="@item.ModelID" class="btn btn-info edit-btn" data-id="@item.ModelID">Edit</a>
                            <a asp-action="DeleteLaptop" asp-route-modelID="@item.ModelID" class="btn btn-danger delete-btn" data-id="@item.ModelID">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a asp-action="NewLaptop" asp-controller="ProductCatalog" class="btn btn-success">New</a>
</div>

Finanstilsynet/Views/ProductCatalog/NewLaptop.cshtml
@using Models

@model Laptop

@{
    ViewData["Title"] = "New Laptop";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-3">
    <h2>@ViewData["Title"]</h2>

    <form id="personalComputerForm" asp-action="SaveNewLaptop" asp-controller="ProductCatalog" method="post">
        <div class="form-group">
            <label asp-for="ModelId">Model ID</label>
            <input asp-for="ModelId" class="form-control" disabled />
            <input type="hidden" asp-for="ModelId" />
        </div>
        <div class="form-group">
            <label asp-for="Speed">PC speed</label>
            <input asp-for="Speed" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Ram">PC RAM</label>
            <input asp-for="Ram" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="HardDisk">Laptop hard disk</label>
            <input asp-for="HardDisk" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Screen">Laptop screen</label>
            <input asp-for="Screen" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" type="number" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <hr />
</div>

Finanstilsynet/Views/ProductCatalog/NewPersonalComputer.cshtml
@using Models

@model Pc

@{
    ViewData["Title"] = "New personal computer";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-3">
    <h2>@ViewData["Title"]</h2>

    <form id="personalComputerForm" asp-action="SaveNewPersonalComputer" asp-controller="ProductCatalog" method="post">
        <div class="form-group">
            <label asp-for="ModelId">Model ID</label>
            <input asp-for="ModelId" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label>Maker ID</label>
            <input value="A" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label>Printer type</label>
            <input value="pc" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label asp-for="Speed"></label>
            <input asp-for="Speed" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Ram"></label>
            <input asp-for="Ram" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="HardDisk"></label>
            <input asp-for="HardDisk" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="ReadDrive"></label>
            <input asp-for="ReadDrive" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" type="number" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <hr />
</div>

Finanstilsynet/Views/ProductCatalog/NewPrinter.cshtml
@using Models

@model Printer

@{
    ViewData["Title"] = "New printer";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-3">
    <h2>@ViewData["Title"]</h2>

    <form id="personalComputerForm" asp-action="SaveNewPrinter" asp-controller="ProductCatalog" method="post">
        <div class="form-group">
            <label asp-for="ModelId">Model ID</label>
            <input asp-for="ModelId" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label>Maker ID</label>
            <input value="A" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label>Printer type</label>
            <input asp-for="Color" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Model">Product Model</label>
            <input asp-for="Model" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Color">Color</label>
            <input asp-for="Color" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <hr />
</div>

Finanstilsynet/Views/ProductCatalog/PersonalComputer.cshtml
@using Models

@model Pc

@{
    ViewData["Title"] = "Manage personal computer";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mt-3">
    <h2>@ViewData["Title"]</h2>

    <form id="personalComputerForm" asp-action="UpdatePc" asp-controller="ProductCatalog" method="post">
        <div class="form-group">
            <label asp-for="ModelId">Model ID</label>
            <input asp-for="ModelId" class="form-control" disabled />
            <input type="hidden" asp-for="ModelId" />
        </div>
        <div class="form-group">
            <label>Maker ID</label>
            <input value="A" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label>Printer type</label>
            <input value="pc" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label asp-for="Speed">PC speed</label>
            <input asp-for="Speed" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Ram">PC RAM</label>
            <input asp-for="Ram" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="HardDisk">PC hard disk</label>
            <input asp-for="HardDisk" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="ReadDrive">PC read drive</label>
            <input asp-for="ReadDrive" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" type="number" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <hr />
</div>

Finanstilsynet/Views/ProductCatalog/PersonalComputers.cshtml
@using ViewModels

@model List<ProductViewModel>

@{
    ViewData["Title"] = "Manage Personal computers";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mb-3">
    <h2>@ViewData["Title"]</h2>
    <hr />
    <table id="productTable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Model ID</th>
                <th>Maker ID</th>
                <th>Printer Type</th>
                <th>PC Speed</th>
                <th>PC RAM</th>
                <th>PC Hard Disk</th>
                <th>PC Read Drive</th>           
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                if (item.Product_Type.Trim().Equals("pc", StringComparison.OrdinalIgnoreCase))
                {                                  
                    <tr>
                        <td>@item.ModelID</td>
                        <td>@item.MakerID</td>
                        <td>@item.Product_Type</td>
                        <td>@item.PC_Speed</td>
                        <td>@item.PC_RAM</td>
                        <td>@item.PC_HardDisk</td>
                        <td>@item.PC_ReadDrive</td>
                        <td>@item.Product_Price</td>
                        <td>
                            <a asp-action="EditPersonalComputer" asp-route-modelID="@item.ModelID" class="btn btn-info edit-btn" data-id="@item.ModelID">Edit</a>
                            <a asp-action="DeletePersonalComputer" asp-route-modelID="@item.ModelID" class="btn btn-danger delete-btn" data-id="@item.ModelID">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a asp-action="NewPersonalComputer" asp-controller="ProductCatalog" class="btn btn-success">New</a>
</div>

Finanstilsynet/Views/ProductCatalog/Printer.cshtml
@using Models

@model Printer

@{
    ViewData["Title"] = "Manage printer";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">



<div class="container mt-3">
    <h2>@ViewData["Title"]</h2>

    <form id="personalComputerForm" asp-action="UpdatePrinter" asp-controller="ProductCatalog" method="post">
        <div class="form-group">
            <label asp-for="ModelId">Model ID</label>
            <input asp-for="ModelId" class="form-control" disabled />
            <input type="hidden" asp-for="ModelId" />
        </div>
        <div class="form-group">
            <label>Maker ID</label>
            <input value="A" class="form-control" disabled />
        </div>
        <div class="form-group">
            <label asp-for="Model">Product Model</label>
            <input asp-for="Model" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price">Price</label>
            <input asp-for="Price" class="form-control" type="number" />
        </div>
        <div class="form-group">
            <label asp-for="Color">Color</label>
            <input asp-for="Color" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <hr />
</div>

Finanstilsynet/Views/ProductCatalog/Printers.cshtml
@using ViewModels

@model List<ProductViewModel>

@{
    ViewData["Title"] = "Manage Printers";
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<div class="container mb-3">
    <h2>@ViewData["Title"]</h2>
    <hr />
    <table id="productTable" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Model ID</th>
                <th>Maker ID</th>
                <th>Printer Type</th>
                <th>Model</th>
                <th>Price</th>
                <th>Color</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                if (item.Product_Type.Trim().Equals("printer", StringComparison.OrdinalIgnoreCase))
                {
                    <tr>
                        <td>@item.ModelID</td>
                        <td>@item.MakerID</td>
                        <td>@item.Product_Type</td>
                        <td>@item.Printer_Type</td>
                        <td>@item.Product_Price</td>
                        <td>@item.Printer_Color</td>
                        <td>
                            <a asp-action="EditPrinter" asp-route-modelID="@item.ModelID" class="btn btn-info edit-btn" data-id="@item.ModelID">Edit</a>
                            <a asp-action="DeletePrinter" asp-route-modelID="@item.ModelID" class="btn btn-danger delete-btn" data-id="@item.ModelID">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a asp-action="NewPrinter" asp-controller="ProductCatalog" class="btn btn-success">New</a>
</div>